spring:
  application:
    name: kafka-streams
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: spring_cloud_config_server_user
      password: '{cipher}f22a63e0a7576d05c62d50a89ea3c905406d67559356af2e594146eda0c451cd'
      allow-override: true
      override-none: true

server:
  port: 9494

encrypt:
  key: ${ENCRYPT_KEY}

eureka:
  client:
    serviceUrl:
      ##############################################################
      # nécessite de mettre à jour le fichier /etc/hosts
      #127.0.0.1          discovery-service-1
      #127.0.0.1          discovery-service-2
      ##############################################################
      defaultZone: http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2