logging:
  level.root: DEBUG


spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: spring_cloud_config_server_user
      password: '{cipher}f22a63e0a7576d05c62d50a89ea3c905406d67559356af2e594146eda0c451cd'
      allow-override: true
      override-none: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

encrypt:
  key: ${ENCRYPT_KEY}

server:
  port: 9590
