version: '3.9'
services:
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    hostname: elastic-1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: nc -z localhost 9200
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - ${GLOBAL_NETWORK:-elastic}
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  data01:
    driver: local