spring:
  application:
    name: twitter-to-kafka
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: spring_cloud_config_server_user
      password: '{cipher}f22a63e0a7576d05c62d50a89ea3c905406d67559356af2e594146eda0c451cd'
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
server:
  port: 9490

encrypt:
  key: ${ENCRYPT_KEY}

log:
  app-name: twitter-to-kafka-service