spring:
  application:
    name: twitter-to-kafka
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: ms-event_config_server_user
      password: ENC(bWhvyU/1MXEbIBQD4uGs4yUPXClvfbZxtym3yiAldi9loZ1MIAa6rKVJoy5VYTLdFTXaMdm2kuEBzJx56CKBeg==)
server:
  port: 9490

jasypt:
  encryptor:
    password: key_encrypt_2022
    algorithm: PBEWITHHMACSHA512ANDAES_256
