twitter-to-kafka-service:
  twitter-keywords:
    - java
    - microservices
    - spring
    - kafka
    - elasticsearch
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 1000

server:
  port: 9490