spring:
  profiles:
    active: singleserver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    appname: service-registry-cluster
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 3
    eviction-interval-timer-in-ms: 2000

---
server:
  port: 8761
spring:
  profiles:
    active: peer1
eureka:
  instance:
    hostname: discovery-service-1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/

---
server:
  port: 8762
spring:
  profiles:
    active: peer2
eureka:
  instance:
    hostname: discovery-service-2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service-2:8762/eureka/,http://discovery-service-1:8761/eureka/