server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexlionnel/ms-twitterevent-config-repo.git
          username: alexlionnel
          password: ENC(LQ8aAs8NSQgMfnbG6PTjRjO1A2V4q6Xr8CzDkUo6fs25N9buhauSsTC4X94pAQe2svkRNQYUVAJ59Dys1vVi6FVVom70ScDL9x++DOAk0fs=)
          clone-on-start: true
          default-label: main
      fail-fast: true
  security:
    user:
      name: ms-event_config_server_user
      password: ENC(bWhvyU/1MXEbIBQD4uGs4yUPXClvfbZxtym3yiAldi9loZ1MIAa6rKVJoy5VYTLdFTXaMdm2kuEBzJx56CKBeg==)

jasypt:
  encryptor:
    password: key_encrypt_2022
    algorithm: PBEWITHHMACSHA512ANDAES_256
